apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  selector:
    matchLabels:
       app: nginx
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
            requests:
              cpu: "200m" 
              memory: "800Mi" 
            limits:
              cpu: "500m" 
              memory: "1200Mi" 
        ports:
        - containerPort: 80
